Computational Take on Statistics: Bootstrapping
========

repeated sampling from a data set, including the bootstrap, jackknife and permutation resampling. 

http://statistics.about.com/od/Applications/a/Example-Of-Bootstrapping.htm


Under usual circumstances, sample sizes of less than 40 cannot be dealt with by assuming a normal distribution or a t distribution. Bootstrap techniques work quite well with samples that have less than 40 elements. 

What about Big Data?

Yes - aggregated.

But often you want to disaggreant / segment
 
or personalize!

In [1]:
import numpy as np

In [6]:
# In any probabilistic simulation, it is prudent to set the random number seed so that results can be replicated
np.random.seed(seed=42)

In [7]:
# Sampling is done with replacement is default
np.random.choice(a=4, size=12,)

array([2, 3, 0, 2, 2, 3, 0, 0, 2, 1, 2, 2])

In [8]:
# Sampling is without replacement
np.random.choice(a=4, size=12, replace=False) 

ValueError: Cannot take a larger sample than population when 'replace=False'

In [9]:
# Sampling is without replacement
np.random.choice(a=4, size=3, replace=False) 

array([0, 1, 3])

In [4]:
# Probability weights can be given
np.random.choice(4, 12, p=[.4, .1, .1, .4])

array([3, 3, 1, 0, 0, 3, 1, 0, 0, 3, 0, 0])

Bootstrap
The bootstrap is commonly used to estimate statistics when a closed form solution may not exist.

In [3]:
from random import choices 

from statistics import mean

In [4]:
data = 1, 2, 4, 4, 10
means = sorted(mean(choices(data, k=5)) 
               for i in range(20))
means

[1.6,
 1.8,
 2.2,
 3,
 3.4,
 3.4,
 3.6,
 3.6,
 3.6,
 3.8,
 3.8,
 4,
 4.2,
 4.6,
 4.6,
 5.2,
 5.2,
 5.2,
 6.4,
 8.8]

Confidence interval

In [30]:
print(f'The sample mean of {mean(data):.1f}')
print(f'90% confidence interval from {means[1]:.1f} to {means[-2]:.1f}')

The sample mean of 4.2
90% confidence interval from 2.4 to 7.2


In [31]:
# TODO: make a function with n samples parameters

In [ ]:
http://people.duke.edu/~ccc14/sta-663-2017/15B_ResamplingAndSimulation.html

-----

In [32]:
# Example from "Statistics is Easy" by Dennis Shasha and Manda Wilson
from statistics import mean

drug = [54, 73, 53, 70, 73, 68, 52, 65, 65]
placebo = [54, 51, 58, 44, 55, 52, 42, 47, 58, 46]
observed_diff = mean(drug) - mean(placebo)

n = 10000
count = 0
combined = drug + placebo
for i in range(n):
    shuffle(combined)
    new_diff = mean(combined[:len(drug)]) - mean(combined[len(drug):])
    count += (new_diff >= observed_diff)

print(f'{n:,} label reshufflings produced only {count} instances with a difference')
print(f'at least as extreme as the observed difference of {observed_diff:.1f}.')
print(f'The one-sided p-value of {count / n:.4f} leads us to reject the null')
print(f'hypothesis that there is no difference between the drug and the placebo.')

10,000 label reshufflings produced only 11 instances with a difference
at least as extreme as the observed difference of 13.0.
The one-sided p-value of 0.0011 leads us to reject the null
hypothesis that there is no difference between the drug and the placebo.


Bonus Material
-----

Simulation of arrival times and service deliveries in a single server queue:

In [33]:
from statistics import mean, median, stdev

average_arrival_interval = 5.6
average_service_time = 5.0
stdev_service_time = 0.5

num_waiting = 0
arrivals = []
starts = []
arrival = service_end = 0.0
for i in range(20000):
    if arrival <= service_end:
        num_waiting += 1
        arrival += expovariate(1.0 / average_arrival_interval)
        arrivals.append(arrival)
    else:
        num_waiting -= 1
        service_start = service_end if num_waiting else arrival
        service_time = gauss(average_service_time, stdev_service_time)
        service_end = service_start + service_time
        starts.append(service_start)

waits = [start - arrival for arrival, start in zip(arrivals, starts)]
print(f'Mean wait: {mean(waits):.1f}.  Stdev wait: {stdev(waits):.1f}.')
print(f'Median wait: {median(waits):.1f}.  Max wait: {max(waits):.1f}.')

Mean wait: 18.8.  Stdev wait: 18.6.
Median wait: 12.8.  Max wait: 100.4.
